# Generated by Django 4.2.13 on 2024-08-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategorycategory',
            new_name='subcategory',
        ),
    ]
